### PR TITLE
Also send explicit Shift for upper case chars (OS X/qemu)

### PR DESCRIPTION
**Pull request by gmanika**
File this one under "hacks", but it appears to work around some still-unknown OS X or qemu issue (my guess is qemu).

### CODE REVIEW

**Comment by smathieu** [comment]
Won't that break the other browsers?

**Comment by gmanika** [comment]
Empirically, it didn't. It wasn't expected to since all this does is send a Shift-down event before upper-case characters. It's just redundant under other operating systems.

**Comment by smathieu** [comment]
Sounds good. I'd feel better if we had ample Rainforest tests for the
various VMs :)

**Comment by gmanika** [comment]
Yeah, I only expect to have solved this particular issue. Not sure which other issues were created by this :)

**Comment by ukd1** [comment]
@jbarber @gallois ...shall we use this?

**Comment by jbarber** [comment]
Fixed independently by https://github.com/rainforestapp/Flashlight-vnc/pull/14

**Pull request closed without merging**
