### PR TITLE
Ctrl key feature

### PR DESCRIPTION
**Pull request by kryptBlue**
Ctrl key works on the client machine, while already implemented Ctrl+V
feature is intact.

//////////////////////////////////////

Also added:
Resolved "Reconnecting message should be visible in the middle of the
screen" issue.

Added a VNCEvent class and its child VNCReconnectEvent class. Moved
VNCErrorEvent class to the aforementioned class hierarchy; it now
extends VNCEvent class.

Added ReconnectingCountDown.mxml which handles displaying of the
reconnect message as described in the issue.

### CODE REVIEW

**Comment by ukd1** [comment]
@smathieu @gmanika what's the status on this?

**Comment by smathieu** [comment]
Basically, we need to revert all of our changes to this project and figure
out which were actually needed. Many of the changes were hacks to get KVM
working correctly, but these issue have now been fixed at the source.

AFAIK, the only changes we made that are useful are the JS callback and
auto reconnect feature.

**Comment by ukd1** [comment]
Is this something only you have knowledge of? is @gmanika up to speed on this?

**Comment by smathieu** [comment]
He should.

**Comment by ukd1** [comment]
@gallois @jbarber any idea wtf this is?

**Comment by gallois** [comment]
nope. I'll take a look later

**Comment by jbarber** [comment]
It appears that these patches add:
* The ability to reconnect if the VNC session is dropped for some reason
* Sending Ctrl to the remote host, rather than just ignoring it

It's not clear to me that we need either feature.

**Comment by jbarber** [comment]
Actually, thinking about the ctrl, it allows you to copy text on the remote host (although maybe not paste as it might be intercepted by flash locally)

**Comment by ukd1** [comment]
@jbarber assigning to you; please close if this is not going to be used / you can't review.

**Pull request closed without merging**
